### ISSUE TITLE
Abode integration "Too many requests" error perhaps exacerbated by ACS add-on?

### ISSUE THREAD

**Issue by bobbeims** [tradel/hassio-addons#13]
This is a follow on to a GitHub ticket I opened against the Abode integration a couple weeks ago: [142563](https://github.com/home-assistant/core/issues/142563)

As described in that ticket, I've been experiencing frequent (and somewhat random) disconnects from the Abode integration due to "too many requests". I haven't discovered a way to programmatically detect the disconnect state, so I tend to only notice it when an automation that should be triggered by an event in my Abode system fails to execute.

Note that I also opened a ticket with the Abode support team that went back and forth for a couple days, which ended with no resolution. They closed the conversation by saying "On the Abode side, there's nothing much we can do as the Home Assistant is not an Abode-supported product."

I'm wondering if my inclusion of the Abode Camera Streaming add-on is exacerbating whatever has changed recently in either the Abode web services config or in some Home Assistant underlying code.

Is there any sort of filtering I could do in the ACS logs to help pinpoint the issue?

**Comment by bobbeims** [comment]
I have the native FFMPEG integration configured to stand up RTSP camera streams. Is that duplicative of what the ACS add-on does?

Here's the YAML I have in my configuration.yaml file:

```
ffmpeg:

camera:
  - platform: ffmpeg
    name: iota RTSP
    input: rtsp://homeassistant.local:8554/iota

  - platform: ffmpeg
    name: Back Porch RTSP
    input: rtsp://homeassistant.local:8554/back_porch

  - platform: ffmpeg
    name: Front Porch RTSP
    input: rtsp://homeassistant.local:8554/front_porch

  - platform: ffmpeg
    name: North Side RTSP
    input: rtsp://homeassistant.local:8554/north_side

  - platform: ffmpeg
    name: Garage RTSP
    input: rtsp://homeassistant.local:8554/garage

  - platform: ffmpeg
    name: Driveway RTSP
    input: rtsp://homeassistant.local:8554/driveway
```
